### ISSUE TITLE
老哥 跑一段时间后 接口调用就返回 403 了怎么解决呀

### ISSUE THREAD

**Issue by xianquan3230** [GzGod/Meshchain#4]
老哥 跑一段时间后 接口调用就返回 403 了怎么解决呀
![image](https://github.com/user-attachments/assets/5913d05e-7292-41fd-9896-df77930841bc)

**Comment by york17** [comment]
我也是一样，是不是被标记黑名单了。403 表示的是服务器拒绝了

**Comment by xianquan3230** [comment]
走代理了啊，而且 我不走代理直接用本地ip 也是 一样返回 403 ，但是 浏览器是能正常访问的

**Comment by YiMoWanXia** [comment]
+1，但是我用postman调用是正常的

**Comment by YiMoWanXia** [comment]
![image](https://github.com/user-attachments/assets/19c75e27-0f01-4212-9a66-c6b3d09ac63e)
这框架是有毒吗，其他的都能调用，就代码调不通

**Comment by xianquan3230** [comment]
协议有问题，换个协议就好了

**Comment by YiMoWanXia** [comment]
咩协议啊？这不就是http协议吗

**Comment by YiMoWanXia** [comment]
咩协议啊？这不就是http协议吗

**Comment by york17** [comment]
> 协议有问题，换个协议就好了

换什么协议？

**Comment by miaomk** [comment]
我用golang写了一套，其中跳过TLS协议去请求是可以执行的。你们用python的可以试一下这个方向

**Comment by york17** [comment]
> 我用golang写了一套，其中跳过TLS协议去请求是可以执行的。你们用python的可以试一下这个方向

我这边代码跳过TLS协议还是不能执行，一样是403。不知道是不是IP被项目方封掉了，但是谷歌浏览器的插件又可以正常领取。肯定是有什么地方是没有注意到

**Comment by miaomk** [comment]
> > 我用golang写了一套，其中跳过TLS协议去请求是可以执行的。你们用python的可以试一下这个方向
> 
> 我这边代码跳过TLS协议还是不能执行，一样是403。不知道是不是IP被项目方封掉了，但是谷歌浏览器的插件又可以正常领取。肯定是有什么地方是没有注意到

可能是官方有反爬虫，你可能需要再加点请求头假装成浏览器或者postman请求避免被盾了。

**Comment by york17** [comment]
> > > 我用golang写了一套，其中跳过TLS协议去请求是可以执行的。你们用python的可以试一下这个方向
> > 
> > 
> > 我这边代码跳过TLS协议还是不能执行，一样是403。不知道是不是IP被项目方封掉了，但是谷歌浏览器的插件又可以正常领取。肯定是有什么地方是没有注意到
> 
> 可能是官方有反爬虫，你可能需要再加点请求头假装成浏览器或者postman请求避免被盾了。

我是用JavaScript写的，请求头已经改成了浏览器的，而且我插件中的请求头的数据，全部拷贝下来设置，也是返回403，有点蛋疼。

**Comment by YiMoWanXia** [comment]
> > > > 我用golang写了一套，其中跳过TLS协议去请求是可以执行的。你们用python的可以试一下这个方向
> > > 
> > > 
> > > 我这边代码跳过TLS协议还是不能执行，一样是403。不知道是不是IP被项目方封掉了，但是谷歌浏览器的插件又可以正常领取。肯定是有什么地方是没有注意到
> > 
> > 
> > 可能是官方有反爬虫，你可能需要再加点请求头假装成浏览器或者postman请求避免被盾了。
> 
> 我是用JavaScript写的，请求头已经改成了浏览器的，而且我插件中的请求头的数据，全部拷贝下来设置，也是返回403，有点蛋疼。

python党已阵亡，java党成功了
`

import javax.net.ssl.*;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.InputStreamReader;
import java.net.*;
import java.security.cert.X509Certificate;
import java.util.HashMap;
import java.util.Map;

/**
 * @author tea
 * @date 2024/12/3
 */
public class MeshChain {

    public static void main(String[] args) {
        try {
            // 设置SOCKS5代理

            // 创建URL对象
            URL url = new URL("https://api.meshchain.ai/meshmain/nodes/status");
            Proxy proxy = new Proxy(Proxy.Type.SOCKS, new InetSocketAddress("10.19.14.34", 7368));
            Authenticator.setDefault(new Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication("C717E3KWRAA", "176864".toCharArray());
                }
            });

            // 打开连接
            HttpsURLConnection connection = (HttpsURLConnection) url.openConnection(proxy);

            // 设置请求方法
            connection.setRequestMethod("POST");

            // 设置请求头
            Map<String, String> headers = new HashMap<>();
            headers.put("Content-Type", "application/json");
            headers.put("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsINsbkEKg3GR5EwqPGDTxI");
            headers.put("Content-Length", "26");
            headers.put("User-Agent", "IntelliJ HTTP Client/PyCharm 2024.3");
            headers.put("Accept-Encoding", "br, deflate, gzip, x-gzip");
            headers.put("Accept", "*/*");
            headers.put("x-http2-scheme", "https");

            for (Map.Entry<String, String> entry : headers.entrySet()) {
                connection.setRequestProperty(entry.getKey(), entry.getValue());
            }

            // 跳过TLS验证
            TrustManager[] trustAllCerts = new TrustManager[]{
                    new X509TrustManager() {
                        public X509Certificate[] getAcceptedIssuers() {
                            return new X509Certificate[0];
                        }

                        public void checkClientTrusted(X509Certificate[] certs, String authType) {
                        }

                        public void checkServerTrusted(X509Certificate[] certs, String authType) {
                        }
                    }
            };

            // SSLContext sc = SSLContext.getInstance("SSL");
            // sc.init(null, trustAllCerts, new java.security.SecureRandom());
            // HttpsURLConnection.setDefaultSSLSocketFactory(sc.getSocketFactory());

            // 创建HostnameVerifier
            HostnameVerifier allHostsValid = (hostname, session) -> true;
            HttpsURLConnection.setDefaultHostnameVerifier(allHostsValid);

            // 发送请求体
            String jsonInputString = "{\"unique_id\": \"5197516311\"}";
            connection.setDoOutput(true);
            try (DataOutputStream wr = new DataOutputStream(connection.getOutputStream())) {
                wr.writeBytes(jsonInputString);
                wr.flush();
            }

            // 读取响应
            int responseCode = connection.getResponseCode();
            System.out.println("Response Code: " + responseCode);

            BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            String inputLine;
            StringBuilder content = new StringBuilder();
            while ((inputLine = in.readLine()) != null) {
                content.append(inputLine);
            }
            in.close();

            // 输出响应内容
            System.out.println(content);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

`

不过java写的没什么吊用
