### ISSUE TITLE
接口调用一直403

### ISSUE THREAD

**Issue by YiMoWanXia** [GzGod/Meshchain#5]
测试代码：

`
import asyncio
import json

import requests

async def main():
    pass

if __name__ == '__main__':
    url = 'https://api.meshchain.ai/meshmain/nodes/status'
    h = {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer token',
        'Content-Length': '26',
        'User-Agent': 'IntelliJ HTTP Client/PyCharm 2024.3',
        'Accept-Encoding': 'br, deflate, gzip, x-gzip',
        'Accept': '*/*',
        'x-http2-scheme': 'https',
    }

    d = {"unique_id": "id"}
    r = requests.post(url, headers=h, data=json.dumps(d))

    print(r.status_code)
`

打印结果403，requests.post带不带proxies都是403

**Comment by miaomk** [comment]
我用golang写了一下，其中跳过TLS协议去请求是可以执行的。你可以试一下这个方向

**Comment by YiMoWanXia** [comment]
我用python的aiohttp.ssl=False&requests.verify=False都没用

**Comment by YiMoWanXia** [comment]
试过了，java没事、go没事，python和js已阵亡
